development:
  adapter: postgresql
  encoding: unicode
  database: projects_development
  pool: 5
  username: kellywaters
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: projects_test
  pool: 5
  username: kellywaters
  password: 